### ISSUE TITLE
Installation via helm chart doesn't work, cert-manager / issuer empty

### ISSUE THREAD

**Issue by markus-arndt-senacor** [kubeshop/testkube#1224]
**Describe the bug**
I'm trying to install testkube on a GKE cluster via Helmchart. After adding the repo, `helm install` fails with an error wrt.`cert-manager.io/v1`.

**To Reproduce**
1. Create a GKE Cluster
2. Add the helm repo via `helm repo add testkube https://kubeshop.github.io/helm-charts`
3. Install testkube via `helm install --create-namespace my-e2e testkube/testkube`

**Expected behavior**
Testkube is installed correctly

**Version / Cluster**
- Which testkube version? **latest?**
- What Kubernetes cluster? **GKE**
- What Kubernetes version? **1.21.9-gke.1002**

**Screenshots**
```
❯ helm install --create-namespace my-e2e testkube/testkube

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"]

```

**Comment by vsukhin** [comment]
Hi @markus-arndt-senacor Cert manager is a required dependency to run testkube at the moment. You can find details about its installation either in readme https://github.com/kubeshop/helm-charts/tree/main/charts/testkube or just go directly to https://cert-manager.io/docs/installation/. We're working on removal of this dependency in order to simplify installation process
