### ISSUE TITLE
K6 executor invalid timing for steps (no start and end time)

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1964]

**Comment by vLia** [comment]
**Steps to Reproduce**
1. Create test suite with tests
2. Get http://localhost:8088/v1/test-suite-with-executions

**Expected behavior**
startTime and endTime in latestExecutions.stepResults.execution is properly populated

**Actual behavior**
startTime is populated, endTime is 0

- Is it only k6?

No, also for other executors

- Does it appear in other /executions endpoint?

Does not appear in 
/tests/${TEST_ID}/executions
/test-suites/${TEST_SUITE_ID}/executions
/executions

Appears in:
/test-suite-with-executions/${TEST_SUITE_ID}
/test-suite-with-executions
