### ISSUE TITLE
Backend: Allow API server to be un-nukable

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2156]
When running multiple k6 tests, the testkube installation stopped working for the user.

related issues:
-  https://github.com/kubeshop/testkube/issues/2084

**Comment by tkonieczny** [comment]
Next step: setting resource `requests` for Testkube pods to make sure they won't be drained of resources.

**Comment by vLia** [comment]
Idea: use queues for executions. When a user starts running a test, it is enqueued. The `executor` listens, and when there is a new test checks for available resources, and runs the test. The resources available to the `executor` could be configured either by the user or auto-discovered somehow from the k8s cluster.

Could also start making the number of parallel tests configurable at first. Adding resource requests to the tests could be a next step.

**Comment by tkonieczny** [comment]
So, the first part of the problem is solved now with resource requests - in case of running too many tests (using up all compute resources) test pods will be evicted/OOMKilled instead of testkube pods. **Testkube remained usable during whole execution.** Request limits for testkube-operator-controller-manager weren't deployed yet.
![Screenshot_20220830_134006](https://user-images.githubusercontent.com/1473096/187429456-a27d753f-7ebf-43c9-a417-c2d78d060a76.png)

**Comment by tkonieczny** [comment]
I created an additional issue: https://github.com/kubeshop/testkube/issues/2187
