### ISSUE TITLE
Java/Maven/Gradle Executor

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#226]
I need to be able to run tests written in Java that use webdriver to automate web/selenium tests

**Comment by lreimer** [comment]
Started working in this issue. While Maven and Gradle are similar, this needs to be implemented as two separate executors. The executor should support execution of the wrapper for Maven and Gradle as well as executor local installations of the two tools. Also, in order to support different JDK versions, I guess there need to be different executor images to support different tool and JDK versions. Working executors are here:
- https://github.com/lreimer/testkube-executor-gradle
- https://github.com/lreimer/testkube-executor-maven

**Comment by exu** [comment]
Closing this one as it's already implemented.
