### ISSUE TITLE
Adding variables will delete the k8s secret created via --git-token

### ISSUE THREAD

**Issue by shanesavoie** [kubeshop/testkube#2594]
**Describe the bug**

When creating a test via CLI, using the `--git-username` or `--secret-variable` flags are dangerous, as any future edits to the variables can inadvertently delete the k8s secret.

The `--git-username-secret` and `--git-token-secret` flags are safe from this behavior.

**To Reproduce**

1. Create a test with --git args:

`kubectl testkube create test --git-uri https://github.com/kubeshop/testkube.git --type k6/script --name test-github-secret-deletion --git-branch master --git-username some-username --git-token some-token`

2. Verify the secret is created:
`kubectl get secrets --namespace testkube | grep test-github-secret-deletion`

3. Add a variable via the UI:
![image](https://user-images.githubusercontent.com/3188939/197222927-cd0dfa75-e470-4397-92a1-2a0d0be1477c.png)

4. Verify that the secret has been deleted:
`kubectl get secrets --namespace testkube | grep test-github-secret-deletion`

**Expected behavior**
Secrets that are generated from the mentioned flags should not be deleted. This will break most tests.
It would be nice if these secrets were visualized in the Variables UI as a Secret Reference.

**Version / Cluster**
- Which testkube version? Helm chart version 1.6.72
- What Kubernetes cluster? EKS
- What Kubernetes version? 1.21

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**

**Comment by vsukhin** [comment]
Thamk you @shanesavoie This is really good point for consideration. But it's more a conceptual question, rather than a bug. CLI create and update commands change the whole test and if any parameter is not provided, then it's either treated as empty or default. But in UI it looks like PATCHing for specific fields rather than the whole test update. Might be we need to intoduce new API method to patch only particular fields, @TheBrunoLopes, @exu?

**Comment by vsukhin** [comment]
Thamk you @shanesavoie This is really good point for consideration. But it's more a conceptual question, rather than a bug. CLI create and update commands change the whole test and if any parameter is not provided, then it's either treated as empty or default. But in UI it looks like PATCHing for specific fields rather than the whole test update. Might be we need to intoduce new API method to patch only particular fields, @TheBrunoLopes, @exu?

**Comment by TheBrunoLopes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2594?planning-poker) with Zenhub @nicufk @vsukhin @vLia @pavloburchak

**Comment by TheBrunoLopes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2594?planning-poker) with Zenhub @TheBrunoLopes
