### ISSUE TITLE
Support AWS-native solution for message bus

### ISSUE THREAD

**Issue by jcogilvie** [kubeshop/testkube#2624]
**Describe the enhancement you'd like to see**
We'd like to see an AWS-native solution for the event bus so we don't have to deploy nats exclusively for testkube.

Options:  SNS, SQS (maybe), EventBridge.

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2624?planning-poker) with Zenhub @nicufk @vLia

**Comment by TheBrunoLopes** [comment]
closing this issue for now, given NATS footprint (5mb) we don't think it would be worth for any company to switch NATS to another message bus. (NATS can send hundreds of thousands of messages with minimal resources usage and without any need to change the default configuration). will reopen in case anyone needs it :)

**Comment by jcogilvie** [comment]
The configuration and deployment footprint is the killer here, not the binary size.  

As an SRE person, my job is to monitor everything, and if I have a standing message bus that you can hook into, it's already monitored, versus bundling testkube with yet another technology that I have to wrap a suite of monitoring around.

**Comment by TheBrunoLopes** [comment]
Hey @jcogilvie seems like we don't have this abstracted in order to use any message queue besides nats and given it's light footprint we haven't seen much maintenance issues related with it.
Let me know if you have a strong need to allow this flexibility of message queues.
and we can work on it. This may be possible to configure for Testkube Enterprise edition.
