### ISSUE TITLE
Error when creating trigger

### ISSUE THREAD

**Issue by scott-david-walker** [kubeshop/testkube#2889]
**Describe the bug**
Attempting to create a trigger via the api or yaml gives an error of:

`Internal error occurred: failed calling webhook \"vtesttrigger.kb.io\": failed to call webhook: Post \"https://testkube-operator-webhook-service.testkube.svc:443/validate-tests-testkube-io-v1-testtrigger?timeout=10s\": no endpoints available for service \"testkube-operator-webhook-service\", context: null"`

**Reproduction Steps**
The exact same reproductions steps as : https://github.com/kubeshop/testkube/issues/2663

- Testkube Version:

  Client Version 1.7.10
  Server Version v1.7.28

- Cluster 
  - AKS

**Additional Information**

The solution in the link above doesn't solve it for me. I deleted the cert and let it recreate but the issue persists.
The "webhooks[0].clientConfig.caBundle" value is filled for me.

**Update**

I'm having the same issue when using minikube. 
The service mentioned (https://testkube-operator-webhook-service) doesn't appear to be pointing at any pod/deployment (judging by the label names)

**Second Update**

This seems to have been introduced on the helm release 1.7.64. Every version following this release has an issue creating triggers. Rolling back to 1.7.63 solves the issue

**Comment by vsukhin** [comment]
thank you @scott-david-walker for reporting it. we will be back to you shortly

**Comment by dejanzele** [comment]
Hello @scott-david-walker,

This issue is known to appear if the webhook create & patch jobs did not successfuly run to completion.

In practice, users removing the Testkube installation using `helm uninstall` and then doing a clean install of the latest version solves the issue.

Can you check do the webhook create & patch jobs complete successfuly after re-install?

Can you please also check does the `caBundle` field in the `testkube-operator-webhook-admission` `ValidatingWebhookConfiguration` matches the `ca.crt` field in the `webhook-server-cert` secret?

**Comment by ypoplavs** [comment]
@scott-david-walker this is a bug in a new release. I will into that shortly!

**Comment by ypoplavs** [comment]
hey @scott-david-walker,

**Comment by ypoplavs** [comment]
@scott-david-walker, there was a typo in `service.yaml` manifest that's why you couldn't create a trigger successfully. 
It is fixed now, please try and let us know if we can do anything for you.

**Comment by scott-david-walker** [comment]
Updated to 1.7.79 and everything seems to be working as expected. Thanks for the quick fix :-)
