### ISSUE TITLE
Executor tests - JMeter test with multiple files

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3450]
Extend executor tests with JMeter test with multiple files. Probably running `git-dir` tests with JMeter isn't currently supported, or at least wasn't tried.
Based on discussion in #3050 : https://github.com/kubeshop/testkube/issues/3050#issuecomment-1476124776
TODO: Create separate enhancement issue after preparing the test and confirming if it's needed

**Comment by AndrewUnderwoodAtFanatics** [comment]
Commenting because I'm interested in staying up to date on this feature.  I was able to make the jmeter executor work with multiple files late last week, though I wouldn't be surprised if what I did breaks when you complete this issue:

I did this running on version `1.9.169` of the helm chart

* Override the jmeter-executor from version [0.0.15](https://github.com/kubeshop/testkube/blob/v1.10.3/config/executors.json#L26) to `0.0.25` to pull in some fixes to how the container starts up
* Add an arg to my test definition that helped the executor figure out which of the files it should be executing
  ```
  executionRequest:
    args:
      - "login-api.xml" # name of the actual jmeter xml files
  ```

Once I did this, I was able to execute a jmeter test with multiple files.

**Comment by tkonieczny** [comment]
@AndrewUnderwoodAtFanatics thanks for letting us know it's already working. There won't be any breaking changes here - we just didn't have tests for this case, and wasn't sure if it's already supported properly.
I just added an additonal test (https://github.com/kubeshop/testkube/pull/3472) - everything looks fine.
