### ISSUE TITLE
Testkube INIT fails due to access forbidden in namespace at cluster scope

### ISSUE THREAD

**Issue by binayaparhy** [kubeshop/testkube#3551]
When I do testkube init it is failing with can not create resource

> testkube init
Current kubectl context: sky-dev-eucentral1
Do you want to continue? [y/n] y
Helm installing testkube framework
Installing testkube (error: process error: exit status 1
output: Release "testkube" does not exist. Installing it now.
Error: namespaces is forbidden: User "https://sts.windows.net/{********}" cannot create resource "namespaces" in API group "" at the cluster scope
)
**Expected behavior**
As it is a corporate cluster, I do not have access to create any resources at cluster scope, so I have to create under a namespace, which is not being possible at the moment. 

If i use --namespace "myparentnamespace/testkube" it is saying / is not allowed

**Comment by ypoplavs** [comment]
Currently we do not support single namespace installation of Testkube. Tagging @TheBrunoLopes to prioritise and discuss this further.

**Comment by TheBrunoLopes** [comment]
Hey @binayaparhy. will discuss with the team tomorrow this issue.
We will comeback to you asap

**Comment by TheBrunoLopes** [comment]
Hey @binayaparhy let me clarify the points from above.
Testkube is deployed in a single namespace with all it's components living there. However, giving its k8s native nature, the testkube operator needs cluster roles to be able to read the CRDs, so in order to deploy it you will need to be able to define them.
