### ISSUE TITLE
UI: add Webhooks to the dashboard

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3920]
AC: 
- UI allows to CRUD webhooks

Figma Design: https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?type=design&node-id=3609-129723&mode=design

**Comment by fivenp** [comment]
Since we have to support custom payloads in the UI we've revisited it and I have attached the new version here: 

https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?type=design&node-id=3609-129723&mode=design

**What this means is:** 

* Webhooks will get a very own menu item on the left
* We will need to switch triggers and sources on the left menu bar
* Webhooks will have a multi-page-view (very similar to triggers)
* I am not sure if there is a way to "test this webhook" on the API yet – it would be a GREAT addition to have (maybe we need to also plan it on the backend)
