### ISSUE TITLE
Remove text autocomplete from Test Create Form

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#4002]
![CleanShot 2023-06-08 at 14 44 06](https://github.com/kubeshop/testkube/assets/27779735/efb7d7d3-7e6a-471b-a997-7e32a0b053ea)

**Comment by Pravesh-Sudha** [comment]
Hey @aabedraba, I would like to work on this

**Comment by aabedraba** [comment]
@Pravesh-Sudha please feel free to open a PR in github.com/kubeshop/testkube-dashboard !

**Comment by Pravesh-Sudha** [comment]
Hey @aabedraba, Sorry for the delay, I didn't get the time to work on the issue, can you please guide me through the particular file as I have been finding it for hours and unable to find it?

**Comment by rangoo94** [comment]
Hi @Pravesh-Sudha,

The "Test name" is available in [**TestCreationForm.tsx**](https://github.com/kubeshop/testkube-dashboard/blob/a3402d5338cb236bf97feef51dc9477641400d61/src/components/pages/Tests/TestsList/TestCreationModalContent/TestCreationForm.tsx#L116) file, but probably worth to add it then to other types of resources (test suites, test sources etc).

It's not *that* simple though to disable the autocompletion, because of its inconsistent implementation. You may add `autocomplete` property with an unrecognized value (i.e. `autocomplete="nope"`) and disable that via ARIA properties (`aria-autocomplete="none"`), so it will work nicely, but still not in 100% cases.

**Comment by Pravesh-Sudha** [comment]
Thanks for the guidance, to make it work 100%, we can set the auto complete to "new password" which will allow the browser to consider the field as new password and typically disabling the auto-complete attribute permanently. 
Will it work for the issue?

**Comment by rangoo94** [comment]
When the browser will consider the name as a "new password", the User will most likely get a few misleading password features. As an example, both the browser and third-party software may try to:

* generate a new password for that name, or
* keep it in the vault as a password after creation, for further reuse

I think that it may lead to more problems than it solves, it's rather better to avoid that.

**Comment by Pravesh-Sudha** [comment]
I have created a new PR with autocomplete = "off" in the input field

**Comment by Pravesh-Sudha** [comment]
Another option would be to specific the name tag with a random string which will make the browser deprive of understanding it as a known string which will not allow it to pass suggestions and thus restricting autoComplete

**Comment by rangoo94** [comment]
Done with https://github.com/kubeshop/testkube-dashboard/pull/889
