### ISSUE TITLE
pytest executor wants files with .py  but /data/test-content has no extension

### ISSUE THREAD

**Issue by jascott1** [kubeshop/testkube#4351]
**Describe the bug**
The pytest executor will not be able to execute string content in `/data/test-content` because pytest only operates on `.py` files. 

**To Reproduce**
Follow the pytest example but change from git repo to string test by creating a python test from file.

Published repo based test:
https://github.com/kubeshop/testkube/blob/develop/contrib/container/pytest/pytest_test.yaml

Modify to string based test:

```
    content:
      data: |-
        import pytest
        import requests

        from requests.exceptions import ConnectionError

        def is_responsive():
            try:
                response = requests.get("https://testkube.io")
                if response.status_code == 200:
                    return False
            except ConnectionError:
                return False

        def test_status():
            assert is_responsive()
      type: string
    executionRequest:
      command:
      - pytest
      - /data
```

**Expected behavior**
Adding executionRequest of 'command: pytest /data' would find the test in /data. Instead pytest cannot find any py files (because none exist).

**Version / Cluster**
- Which testkube version?  1.14.3
- What Kubernetes cluster? local kubadm
- What Kubernetes version? v1.26.1
 
**Additional context**
You can change the filename pattern pytest looks for easily (pytest -o python_files=test-content) but files are still required to have `.py` extension so that fails. Also, thanks for the great software!

**Comment by vsukhin** [comment]
Hey, @jascott1 
Thank you for your good words!
The idea behind container executor is to allow our users fully define executor behaivour
That's why we provided a Docker file instead of pre-built image
And having in mind that Python is a separate universe, we can't satisfy all requirements in advance
You have multiple options to ahceive your goals:
1. Add one more RUJN command to docker file for renaming test-content file
2. Rename this file in prerun script
3. Or just use git repo to keep file/folder structure

**Comment by vsukhin** [comment]
closing, let us know, if above is not enough

**Comment by jascott1** [comment]
@vsukhin Thanks for the helpful response! I understand now and just added a run.sh to the container that copies the test-content to test_content.py.
