### ISSUE TITLE
no kind "TestSource" is registered for version "tests.testkube.io/v1" in scheme

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#4903]
**Describe the bug**

```
W0117 11:56:08.543073       1 reflector.go:458] pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: watch of *v1.TestSource ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"TestSource\" is registered for version \"tests.testkube.io/v1\" in scheme \"pkg/runtime/scheme.go:100\"") has prevented the request from succeeding
```

**Comment by jerem0808** [comment]
Hi @vsukhin 
I still have this error in the helm chart 1.16.29
`W0213 06:54:06.476909       1 reflector.go:458] pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: watch of *v1.TestSource ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"TestSource\" is registered for version \"tests.testkube.io/v1\" in scheme \"pkg/runtime/scheme.go:100\"") has prevented the request from succeeding`

Is it the same error?
Because I have in the dashboard a never ending loading of Tests.

`NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART           	APP VERSION
testkube	testkube 	4       	2024-02-13 07:58:46.170117453 +0100 CET	deployed	testkube-1.16.29`

**Comment by vsukhin** [comment]
Can you try the latest one? I don't remember it was precise helm chart it was fixed

**Comment by jerem0808** [comment]
I am using the latest helm chart. I pulled the chart and pushed it in our local repo.

**Comment by vsukhin** [comment]
https://github.com/kubeshop/helm-charts/releases/tag/testkube-1.16.38

**Comment by jerem0808** [comment]
But the tag latest is set on .27 right?

![image](https://github.com/kubeshop/testkube/assets/4958851/877a81c4-49d0-4ee8-be79-d786ff9fa54b)
